[package]
name = "rust"
version = "0.1.0"
authors = ["Vadasz Laszlo <maxinteger@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
lto = true
